In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

n_samples = 1500
dataset = datasets.make_blobs(n_samples=n_samples, centers=2, center_box=(-7.0, 7.5),
                              cluster_std=[1.4, 1.7],
                              random_state=42)
X_2, _ = datasets.make_blobs(n_samples=n_samples, random_state=170, centers=[[-4, -3]], cluster_std=[1.9])
transformation = [[1.2, -0.8], [-0.4, 1.7]]
X_2 = np.dot(X_2, transformation)
X, y = np.concatenate((dataset[0], X_2)), np.concatenate((dataset[1], np.array([2] * len(X_2))))


[-1  0  1  2]
368 656 721 1255 

In [2]:
plt.rcParams['figure.figsize'] = 10, 10
plt.scatter(X[:, 0], X[:, 1], c=y, alpha=0.5)
plt.show()


[-1  0  1  2]
368 656 721 1255 

In [8]:
# 4.8.2
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=0.9, min_samples=35)
dbscan.fit(X)
y_pred = dbscan.labels_.astype(np.int)
_, counts = np.unique(y_pred, return_counts=True)
print(np.unique(y_pred))
for count in counts:
    print(count, end=' ')


[-1  0  1  2]
368 656 721 1255 

In [10]:
# 4.8.3
counts[-1]


1255

In [11]:
# 4.8.4
dbscan = DBSCAN(eps=0.8, min_samples=35)
dbscan.fit(X)
y_pred = dbscan.labels_.astype(np.int)
_, counts = np.unique(y_pred, return_counts=True)
print(np.unique(y_pred))
for count in counts:
    print(count, end=' ')
counts[-1]


[-1  0  1  2]
583 603 681 1133 

1133